#!/bin/bash

#                  ,$$$$$',$$$$$',$$$$$'
#                 ,$$$$$',$$$$$',$$$$$'           - - -- ---- ✈
#                ,$$$$$',$$$$$',$$$$$'   ᕦ(ò_óˇ)ᕤ いきましょう！
#               ,s$$$$',$$$$$',$$$$$'
#              ,$$$$$',$$$$$',$$$$$'       SΙΤΞΚ SYSTΞMS ©1985
#             ,$$$$$',$$$$$',$$$$$'

#             Disclaimer: This SOFTWARE PRODUCT is provided
#             by THE PROVIDER "as is", with all faults and
#             without warranty of any kind.
#
#             SΙΤΞΚ SYSTΞMS ©1985. All rights Reserved.

#///////////////////////////////////////////////////////////////////////////////

version: '2'

services:
  postgres:
    container_name: db
    image: postgres:9.6
    volumes:
      - ~/projects/db_data:/var/lib/postgresql/data
      - /var/run/postgresql
    ports:
      - 5432:5432

  # mysql:
  #   container_name: db
  #   image: mysql:8
  #   volumes:
  #     - ~/projects/db_data:/var/lib/mysql
  #     - /var/run/mysqld
  #   ports:
  #     - 3306:3306

  rails:
    image: railsbox
    build: ${DEVBOX_ROOT_PATH}/boxes/railsbox
    volumes:
      - .:/home/devbox/app
    volumes_from:
      - db
    external_links:
      - db
    ports:
      - 3000:3000
